// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ban {
    pub identity: __sdk::Identity,
    pub reason: String,
}

impl __sdk::InModule for Ban {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Ban`.
///
/// Provides typed access to columns for query building.
pub struct BanCols {
    pub identity: __sdk::__query_builder::Col<Ban, __sdk::Identity>,
    pub reason: __sdk::__query_builder::Col<Ban, String>,
}

impl __sdk::__query_builder::HasCols for Ban {
    type Cols = BanCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BanCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
        }
    }
}

/// Indexed column accessor struct for the table `Ban`.
///
/// Provides typed access to indexed columns for query building.
pub struct BanIxCols {
    pub identity: __sdk::__query_builder::IxCol<Ban, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Ban {
    type IxCols = BanIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BanIxCols { identity: __sdk::__query_builder::IxCol::new(table_name, "identity") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ban {}
