// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FighterRow {
    pub player: u16,
    pub shield: f32,
    pub body: f32,
    pub shield_stun_ticks: i16,
    pub flags: u8,
    pub tick: u64,
    pub weapon_0: u16,
    pub weapon_1: u16,
    pub dropped_0: u16,
    pub dropped_0_tick: u64,
    pub dropped_1: u16,
    pub dropped_1_tick: u64,
    pub hurt_tick: u64,
    pub hurt_by: u16,
    pub hurt_count: u32,
}

impl __sdk::InModule for FighterRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FighterRow`.
///
/// Provides typed access to columns for query building.
pub struct FighterRowCols {
    pub player: __sdk::__query_builder::Col<FighterRow, u16>,
    pub shield: __sdk::__query_builder::Col<FighterRow, f32>,
    pub body: __sdk::__query_builder::Col<FighterRow, f32>,
    pub shield_stun_ticks: __sdk::__query_builder::Col<FighterRow, i16>,
    pub flags: __sdk::__query_builder::Col<FighterRow, u8>,
    pub tick: __sdk::__query_builder::Col<FighterRow, u64>,
    pub weapon_0: __sdk::__query_builder::Col<FighterRow, u16>,
    pub weapon_1: __sdk::__query_builder::Col<FighterRow, u16>,
    pub dropped_0: __sdk::__query_builder::Col<FighterRow, u16>,
    pub dropped_0_tick: __sdk::__query_builder::Col<FighterRow, u64>,
    pub dropped_1: __sdk::__query_builder::Col<FighterRow, u16>,
    pub dropped_1_tick: __sdk::__query_builder::Col<FighterRow, u64>,
    pub hurt_tick: __sdk::__query_builder::Col<FighterRow, u64>,
    pub hurt_by: __sdk::__query_builder::Col<FighterRow, u16>,
    pub hurt_count: __sdk::__query_builder::Col<FighterRow, u32>,
}

impl __sdk::__query_builder::HasCols for FighterRow {
    type Cols = FighterRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FighterRowCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            shield: __sdk::__query_builder::Col::new(table_name, "shield"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
            shield_stun_ticks: __sdk::__query_builder::Col::new(table_name, "shield_stun_ticks"),
            flags: __sdk::__query_builder::Col::new(table_name, "flags"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            weapon_0: __sdk::__query_builder::Col::new(table_name, "weapon_0"),
            weapon_1: __sdk::__query_builder::Col::new(table_name, "weapon_1"),
            dropped_0: __sdk::__query_builder::Col::new(table_name, "dropped_0"),
            dropped_0_tick: __sdk::__query_builder::Col::new(table_name, "dropped_0_tick"),
            dropped_1: __sdk::__query_builder::Col::new(table_name, "dropped_1"),
            dropped_1_tick: __sdk::__query_builder::Col::new(table_name, "dropped_1_tick"),
            hurt_tick: __sdk::__query_builder::Col::new(table_name, "hurt_tick"),
            hurt_by: __sdk::__query_builder::Col::new(table_name, "hurt_by"),
            hurt_count: __sdk::__query_builder::Col::new(table_name, "hurt_count"),
        }
    }
}

/// Indexed column accessor struct for the table `FighterRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct FighterRowIxCols {
    pub player: __sdk::__query_builder::IxCol<FighterRow, u16>,
}

impl __sdk::__query_builder::HasIxCols for FighterRow {
    type IxCols = FighterRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FighterRowIxCols { player: __sdk::__query_builder::IxCol::new(table_name, "player") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FighterRow {}
