// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::fighter_row_type::FighterRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fighter`.
///
/// Obtain a handle from the [`FighterTableAccess::fighter`] method on [`super::RemoteTables`],
/// like `ctx.db.fighter()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fighter().on_insert(...)`.
pub struct FighterTableHandle<'ctx> {
    imp: __sdk::TableHandle<FighterRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `fighter`.
pub struct FighterTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for FighterTableAccessor {
    type Row = FighterRow;
    type Handle<'db> = FighterTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.fighter()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fighter`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FighterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FighterTableHandle`], which mediates access to the table `fighter`.
    fn fighter(&self) -> FighterTableHandle<'_>;
}

impl FighterTableAccess for super::RemoteTables {
    fn fighter(&self) -> FighterTableHandle<'_> {
        FighterTableHandle { imp: self.imp.get_table::<FighterRow>("fighter"), ctx: std::marker::PhantomData }
    }
}

pub struct FighterInsertCallbackId(__sdk::CallbackId);
pub struct FighterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for FighterTableHandle<'ctx> {
    type Row = FighterRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FighterRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for FighterTableHandle<'ctx> {
    type Row = FighterRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FighterRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FighterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FighterInsertCallbackId {
        FighterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FighterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FighterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FighterDeleteCallbackId {
        FighterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FighterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for FighterTableHandle<'ctx> {
    type InsertCallbackId = FighterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FighterInsertCallbackId {
        FighterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FighterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for FighterTableHandle<'ctx> {
    type DeleteCallbackId = FighterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FighterDeleteCallbackId {
        FighterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FighterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FighterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FighterTableHandle<'ctx> {
    type UpdateCallbackId = FighterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FighterUpdateCallbackId {
        FighterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FighterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for FighterTableHandle<'ctx> {
    type UpdateCallbackId = FighterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FighterUpdateCallbackId {
        FighterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FighterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player` unique index on the table `fighter`,
/// which allows point queries on the field of the same name
/// via the [`FighterPlayerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fighter().player().find(...)`.
pub struct FighterPlayerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FighterRow, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FighterTableHandle<'ctx> {
    /// Get a handle on the `player` unique index on the table `fighter`.
    pub fn player(&self) -> FighterPlayerUnique<'ctx> {
        FighterPlayerUnique { imp: self.imp.get_unique_constraint::<u16>("player"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> FighterPlayerUnique<'ctx> {
    /// Find the subscribed row whose `player` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<FighterRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FighterRow>("fighter");
    _table.add_unique_constraint::<u16>("player", |row| &row.player);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<FighterRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<FighterRow>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FighterRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait fighterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FighterRow`.
    fn fighter(&self) -> __sdk::__query_builder::Table<FighterRow>;
}

impl fighterQueryTableAccess for __sdk::QueryTableAccessor {
    fn fighter(&self) -> __sdk::__query_builder::Table<FighterRow> {
        __sdk::__query_builder::Table::new("fighter")
    }
}
