// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameStateRow {
    pub id: u8,
    pub teams: bool,
    pub score_limit: u32,
    pub time_limit_ticks: u32,
    pub respawn_ticks: u32,
    pub respawn_growth_ticks: u32,
    pub suicide_penalty_ticks: u32,
    pub wave_ticks: u32,
    pub started_tick: u64,
    pub tick: u64,
    pub red_score: i32,
    pub blue_score: i32,
    pub ending: u8,
    pub winner_kind: u8,
    pub winner: u16,
}

impl __sdk::InModule for GameStateRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameStateRow`.
///
/// Provides typed access to columns for query building.
pub struct GameStateRowCols {
    pub id: __sdk::__query_builder::Col<GameStateRow, u8>,
    pub teams: __sdk::__query_builder::Col<GameStateRow, bool>,
    pub score_limit: __sdk::__query_builder::Col<GameStateRow, u32>,
    pub time_limit_ticks: __sdk::__query_builder::Col<GameStateRow, u32>,
    pub respawn_ticks: __sdk::__query_builder::Col<GameStateRow, u32>,
    pub respawn_growth_ticks: __sdk::__query_builder::Col<GameStateRow, u32>,
    pub suicide_penalty_ticks: __sdk::__query_builder::Col<GameStateRow, u32>,
    pub wave_ticks: __sdk::__query_builder::Col<GameStateRow, u32>,
    pub started_tick: __sdk::__query_builder::Col<GameStateRow, u64>,
    pub tick: __sdk::__query_builder::Col<GameStateRow, u64>,
    pub red_score: __sdk::__query_builder::Col<GameStateRow, i32>,
    pub blue_score: __sdk::__query_builder::Col<GameStateRow, i32>,
    pub ending: __sdk::__query_builder::Col<GameStateRow, u8>,
    pub winner_kind: __sdk::__query_builder::Col<GameStateRow, u8>,
    pub winner: __sdk::__query_builder::Col<GameStateRow, u16>,
}

impl __sdk::__query_builder::HasCols for GameStateRow {
    type Cols = GameStateRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameStateRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            teams: __sdk::__query_builder::Col::new(table_name, "teams"),
            score_limit: __sdk::__query_builder::Col::new(table_name, "score_limit"),
            time_limit_ticks: __sdk::__query_builder::Col::new(table_name, "time_limit_ticks"),
            respawn_ticks: __sdk::__query_builder::Col::new(table_name, "respawn_ticks"),
            respawn_growth_ticks: __sdk::__query_builder::Col::new(table_name, "respawn_growth_ticks"),
            suicide_penalty_ticks: __sdk::__query_builder::Col::new(table_name, "suicide_penalty_ticks"),
            wave_ticks: __sdk::__query_builder::Col::new(table_name, "wave_ticks"),
            started_tick: __sdk::__query_builder::Col::new(table_name, "started_tick"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            red_score: __sdk::__query_builder::Col::new(table_name, "red_score"),
            blue_score: __sdk::__query_builder::Col::new(table_name, "blue_score"),
            ending: __sdk::__query_builder::Col::new(table_name, "ending"),
            winner_kind: __sdk::__query_builder::Col::new(table_name, "winner_kind"),
            winner: __sdk::__query_builder::Col::new(table_name, "winner"),
        }
    }
}

/// Indexed column accessor struct for the table `GameStateRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameStateRowIxCols {
    pub id: __sdk::__query_builder::IxCol<GameStateRow, u8>,
}

impl __sdk::__query_builder::HasIxCols for GameStateRow {
    type IxCols = GameStateRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameStateRowIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameStateRow {}
