// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HitReportRow {
    pub id: u64,
    pub shooter: u16,
    pub data: Vec<u8>,
}

impl __sdk::InModule for HitReportRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HitReportRow`.
///
/// Provides typed access to columns for query building.
pub struct HitReportRowCols {
    pub id: __sdk::__query_builder::Col<HitReportRow, u64>,
    pub shooter: __sdk::__query_builder::Col<HitReportRow, u16>,
    pub data: __sdk::__query_builder::Col<HitReportRow, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for HitReportRow {
    type Cols = HitReportRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HitReportRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            shooter: __sdk::__query_builder::Col::new(table_name, "shooter"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `HitReportRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct HitReportRowIxCols {
    pub id: __sdk::__query_builder::IxCol<HitReportRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for HitReportRow {
    type IxCols = HitReportRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HitReportRowIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HitReportRow {}
