// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InputBatch {
    pub id: u64,
    pub data: Vec<u8>,
}

impl __sdk::InModule for InputBatch {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InputBatch`.
///
/// Provides typed access to columns for query building.
pub struct InputBatchCols {
    pub id: __sdk::__query_builder::Col<InputBatch, u64>,
    pub data: __sdk::__query_builder::Col<InputBatch, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for InputBatch {
    type Cols = InputBatchCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InputBatchCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `InputBatch`.
///
/// Provides typed access to indexed columns for query building.
pub struct InputBatchIxCols {
    pub id: __sdk::__query_builder::IxCol<InputBatch, u64>,
}

impl __sdk::__query_builder::HasIxCols for InputBatch {
    type IxCols = InputBatchIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InputBatchIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InputBatch {}
