// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_row_type::ItemRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item`.
///
/// Obtain a handle from the [`ItemTableAccess::item`] method on [`super::RemoteTables`],
/// like `ctx.db.item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item().on_insert(...)`.
pub struct ItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `item`.
pub struct ItemTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ItemTableAccessor {
    type Row = ItemRow;
    type Handle<'db> = ItemTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.item()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemTableHandle`], which mediates access to the table `item`.
    fn item(&self) -> ItemTableHandle<'_>;
}

impl ItemTableAccess for super::RemoteTables {
    fn item(&self) -> ItemTableHandle<'_> {
        ItemTableHandle { imp: self.imp.get_table::<ItemRow>("item"), ctx: std::marker::PhantomData }
    }
}

pub struct ItemInsertCallbackId(__sdk::CallbackId);
pub struct ItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ItemTableHandle<'ctx> {
    type Row = ItemRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ItemTableHandle<'ctx> {
    type Row = ItemRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemInsertCallbackId {
        ItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDeleteCallbackId {
        ItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ItemTableHandle<'ctx> {
    type InsertCallbackId = ItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemInsertCallbackId {
        ItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ItemTableHandle<'ctx> {
    type DeleteCallbackId = ItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDeleteCallbackId {
        ItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemTableHandle<'ctx> {
    type UpdateCallbackId = ItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemUpdateCallbackId {
        ItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ItemTableHandle<'ctx> {
    type UpdateCallbackId = ItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemUpdateCallbackId {
        ItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `item`,
/// which allows point queries on the field of the same name
/// via the [`ItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item().id().find(...)`.
pub struct ItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemRow, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `item`.
    pub fn id(&self) -> ItemIdUnique<'ctx> {
        ItemIdUnique { imp: self.imp.get_unique_constraint::<u32>("id"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> ItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ItemRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemRow>("item");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<ItemRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<ItemRow>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ItemRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ItemRow`.
    fn item(&self) -> __sdk::__query_builder::Table<ItemRow>;
}

impl itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn item(&self) -> __sdk::__query_builder::Table<ItemRow> {
        __sdk::__query_builder::Table::new("item")
    }
}
