// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemRow {
    pub id: u32,
    pub tag: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub vx: f32,
    pub vy: f32,
    pub vz: f32,
    pub tick: u64,
    pub resting: bool,
    pub placement: u16,
    pub loaded: i16,
    pub reserve: i16,
    pub last_owned: u64,
    pub ignore: u16,
}

impl __sdk::InModule for ItemRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ItemRow`.
///
/// Provides typed access to columns for query building.
pub struct ItemRowCols {
    pub id: __sdk::__query_builder::Col<ItemRow, u32>,
    pub tag: __sdk::__query_builder::Col<ItemRow, u16>,
    pub x: __sdk::__query_builder::Col<ItemRow, f32>,
    pub y: __sdk::__query_builder::Col<ItemRow, f32>,
    pub z: __sdk::__query_builder::Col<ItemRow, f32>,
    pub vx: __sdk::__query_builder::Col<ItemRow, f32>,
    pub vy: __sdk::__query_builder::Col<ItemRow, f32>,
    pub vz: __sdk::__query_builder::Col<ItemRow, f32>,
    pub tick: __sdk::__query_builder::Col<ItemRow, u64>,
    pub resting: __sdk::__query_builder::Col<ItemRow, bool>,
    pub placement: __sdk::__query_builder::Col<ItemRow, u16>,
    pub loaded: __sdk::__query_builder::Col<ItemRow, i16>,
    pub reserve: __sdk::__query_builder::Col<ItemRow, i16>,
    pub last_owned: __sdk::__query_builder::Col<ItemRow, u64>,
    pub ignore: __sdk::__query_builder::Col<ItemRow, u16>,
}

impl __sdk::__query_builder::HasCols for ItemRow {
    type Cols = ItemRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ItemRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            tag: __sdk::__query_builder::Col::new(table_name, "tag"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            vx: __sdk::__query_builder::Col::new(table_name, "vx"),
            vy: __sdk::__query_builder::Col::new(table_name, "vy"),
            vz: __sdk::__query_builder::Col::new(table_name, "vz"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            resting: __sdk::__query_builder::Col::new(table_name, "resting"),
            placement: __sdk::__query_builder::Col::new(table_name, "placement"),
            loaded: __sdk::__query_builder::Col::new(table_name, "loaded"),
            reserve: __sdk::__query_builder::Col::new(table_name, "reserve"),
            last_owned: __sdk::__query_builder::Col::new(table_name, "last_owned"),
            ignore: __sdk::__query_builder::Col::new(table_name, "ignore"),
        }
    }
}

/// Indexed column accessor struct for the table `ItemRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ItemRowIxCols {
    pub id: __sdk::__query_builder::IxCol<ItemRow, u32>,
}

impl __sdk::__query_builder::HasIxCols for ItemRow {
    type IxCols = ItemRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ItemRowIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ItemRow {}
