// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::kit_row_type::KitRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `kit`.
///
/// Obtain a handle from the [`KitTableAccess::kit`] method on [`super::RemoteTables`],
/// like `ctx.db.kit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.kit().on_insert(...)`.
pub struct KitTableHandle<'ctx> {
    imp: __sdk::TableHandle<KitRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `kit`.
pub struct KitTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for KitTableAccessor {
    type Row = KitRow;
    type Handle<'db> = KitTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.kit()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `kit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KitTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KitTableHandle`], which mediates access to the table `kit`.
    fn kit(&self) -> KitTableHandle<'_>;
}

impl KitTableAccess for super::RemoteTables {
    fn kit(&self) -> KitTableHandle<'_> {
        KitTableHandle { imp: self.imp.get_table::<KitRow>("kit"), ctx: std::marker::PhantomData }
    }
}

pub struct KitInsertCallbackId(__sdk::CallbackId);
pub struct KitDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for KitTableHandle<'ctx> {
    type Row = KitRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KitRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for KitTableHandle<'ctx> {
    type Row = KitRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KitRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KitInsertCallbackId;

    fn on_insert(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> KitInsertCallbackId {
        KitInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KitInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KitDeleteCallbackId;

    fn on_delete(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> KitDeleteCallbackId {
        KitDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KitDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for KitTableHandle<'ctx> {
    type InsertCallbackId = KitInsertCallbackId;

    fn on_insert(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> KitInsertCallbackId {
        KitInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KitInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for KitTableHandle<'ctx> {
    type DeleteCallbackId = KitDeleteCallbackId;

    fn on_delete(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> KitDeleteCallbackId {
        KitDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KitDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct KitUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KitTableHandle<'ctx> {
    type UpdateCallbackId = KitUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KitUpdateCallbackId {
        KitUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KitUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for KitTableHandle<'ctx> {
    type UpdateCallbackId = KitUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KitUpdateCallbackId {
        KitUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KitUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player` unique index on the table `kit`,
/// which allows point queries on the field of the same name
/// via the [`KitPlayerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.kit().player().find(...)`.
pub struct KitPlayerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<KitRow, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> KitTableHandle<'ctx> {
    /// Get a handle on the `player` unique index on the table `kit`.
    pub fn player(&self) -> KitPlayerUnique<'ctx> {
        KitPlayerUnique { imp: self.imp.get_unique_constraint::<u16>("player"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> KitPlayerUnique<'ctx> {
    /// Find the subscribed row whose `player` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<KitRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<KitRow>("kit");
    _table.add_unique_constraint::<u16>("player", |row| &row.player);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<KitRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<KitRow>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `KitRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait kitQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `KitRow`.
    fn kit(&self) -> __sdk::__query_builder::Table<KitRow>;
}

impl kitQueryTableAccess for __sdk::QueryTableAccessor {
    fn kit(&self) -> __sdk::__query_builder::Table<KitRow> {
        __sdk::__query_builder::Table::new("kit")
    }
}
