// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct KitRow {
    pub player: u16,
    pub loaded_0: i16,
    pub reserve_0: i16,
    pub loaded_1: i16,
    pub reserve_1: i16,
    pub version: u32,
    pub frag: u8,
    pub plasma: u8,
}

impl __sdk::InModule for KitRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `KitRow`.
///
/// Provides typed access to columns for query building.
pub struct KitRowCols {
    pub player: __sdk::__query_builder::Col<KitRow, u16>,
    pub loaded_0: __sdk::__query_builder::Col<KitRow, i16>,
    pub reserve_0: __sdk::__query_builder::Col<KitRow, i16>,
    pub loaded_1: __sdk::__query_builder::Col<KitRow, i16>,
    pub reserve_1: __sdk::__query_builder::Col<KitRow, i16>,
    pub version: __sdk::__query_builder::Col<KitRow, u32>,
    pub frag: __sdk::__query_builder::Col<KitRow, u8>,
    pub plasma: __sdk::__query_builder::Col<KitRow, u8>,
}

impl __sdk::__query_builder::HasCols for KitRow {
    type Cols = KitRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        KitRowCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            loaded_0: __sdk::__query_builder::Col::new(table_name, "loaded_0"),
            reserve_0: __sdk::__query_builder::Col::new(table_name, "reserve_0"),
            loaded_1: __sdk::__query_builder::Col::new(table_name, "loaded_1"),
            reserve_1: __sdk::__query_builder::Col::new(table_name, "reserve_1"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            frag: __sdk::__query_builder::Col::new(table_name, "frag"),
            plasma: __sdk::__query_builder::Col::new(table_name, "plasma"),
        }
    }
}

/// Indexed column accessor struct for the table `KitRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct KitRowIxCols {
    pub player: __sdk::__query_builder::IxCol<KitRow, u16>,
}

impl __sdk::__query_builder::HasIxCols for KitRow {
    type IxCols = KitRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        KitRowIxCols { player: __sdk::__query_builder::IxCol::new(table_name, "player") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for KitRow {}
