// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MapInfo {
    pub id: u8,
    pub version: u64,
    pub x_0: f32,
    pub x_1: f32,
    pub y_0: f32,
    pub y_1: f32,
    pub z_0: f32,
    pub z_1: f32,
}

impl __sdk::InModule for MapInfo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MapInfo`.
///
/// Provides typed access to columns for query building.
pub struct MapInfoCols {
    pub id: __sdk::__query_builder::Col<MapInfo, u8>,
    pub version: __sdk::__query_builder::Col<MapInfo, u64>,
    pub x_0: __sdk::__query_builder::Col<MapInfo, f32>,
    pub x_1: __sdk::__query_builder::Col<MapInfo, f32>,
    pub y_0: __sdk::__query_builder::Col<MapInfo, f32>,
    pub y_1: __sdk::__query_builder::Col<MapInfo, f32>,
    pub z_0: __sdk::__query_builder::Col<MapInfo, f32>,
    pub z_1: __sdk::__query_builder::Col<MapInfo, f32>,
}

impl __sdk::__query_builder::HasCols for MapInfo {
    type Cols = MapInfoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MapInfoCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            x_0: __sdk::__query_builder::Col::new(table_name, "x_0"),
            x_1: __sdk::__query_builder::Col::new(table_name, "x_1"),
            y_0: __sdk::__query_builder::Col::new(table_name, "y_0"),
            y_1: __sdk::__query_builder::Col::new(table_name, "y_1"),
            z_0: __sdk::__query_builder::Col::new(table_name, "z_0"),
            z_1: __sdk::__query_builder::Col::new(table_name, "z_1"),
        }
    }
}

/// Indexed column accessor struct for the table `MapInfo`.
///
/// Provides typed access to indexed columns for query building.
pub struct MapInfoIxCols {
    pub id: __sdk::__query_builder::IxCol<MapInfo, u8>,
}

impl __sdk::__query_builder::HasIxCols for MapInfo {
    type IxCols = MapInfoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MapInfoIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MapInfo {}
