// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_info_type::MapInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_info`.
///
/// Obtain a handle from the [`MapInfoTableAccess::map_info`] method on [`super::RemoteTables`],
/// like `ctx.db.map_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_info().on_insert(...)`.
pub struct MapInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `map_info`.
pub struct MapInfoTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MapInfoTableAccessor {
    type Row = MapInfo;
    type Handle<'db> = MapInfoTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.map_info()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapInfoTableHandle`], which mediates access to the table `map_info`.
    fn map_info(&self) -> MapInfoTableHandle<'_>;
}

impl MapInfoTableAccess for super::RemoteTables {
    fn map_info(&self) -> MapInfoTableHandle<'_> {
        MapInfoTableHandle { imp: self.imp.get_table::<MapInfo>("map_info"), ctx: std::marker::PhantomData }
    }
}

pub struct MapInfoInsertCallbackId(__sdk::CallbackId);
pub struct MapInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MapInfoTableHandle<'ctx> {
    type Row = MapInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapInfo> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MapInfoTableHandle<'ctx> {
    type Row = MapInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInfoInsertCallbackId {
        MapInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInfoDeleteCallbackId {
        MapInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MapInfoTableHandle<'ctx> {
    type InsertCallbackId = MapInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInfoInsertCallbackId {
        MapInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MapInfoTableHandle<'ctx> {
    type DeleteCallbackId = MapInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInfoDeleteCallbackId {
        MapInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MapInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapInfoTableHandle<'ctx> {
    type UpdateCallbackId = MapInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapInfoUpdateCallbackId {
        MapInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MapInfoTableHandle<'ctx> {
    type UpdateCallbackId = MapInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapInfoUpdateCallbackId {
        MapInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `map_info`,
/// which allows point queries on the field of the same name
/// via the [`MapInfoIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_info().id().find(...)`.
pub struct MapInfoIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapInfo, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapInfoTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `map_info`.
    pub fn id(&self) -> MapInfoIdUnique<'ctx> {
        MapInfoIdUnique { imp: self.imp.get_unique_constraint::<u8>("id"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> MapInfoIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<MapInfo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapInfo>("map_info");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<MapInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<MapInfo>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait map_infoQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapInfo`.
    fn map_info(&self) -> __sdk::__query_builder::Table<MapInfo>;
}

impl map_infoQueryTableAccess for __sdk::QueryTableAccessor {
    fn map_info(&self) -> __sdk::__query_builder::Table<MapInfo> {
        __sdk::__query_builder::Table::new("map_info")
    }
}
