// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchConfig {
    pub id: u8,
    pub owner: __sdk::Identity,
    pub gateway: __sdk::Identity,
    pub capacity: u16,
    pub away_grace_ticks: u64,
}

impl __sdk::InModule for MatchConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchConfig`.
///
/// Provides typed access to columns for query building.
pub struct MatchConfigCols {
    pub id: __sdk::__query_builder::Col<MatchConfig, u8>,
    pub owner: __sdk::__query_builder::Col<MatchConfig, __sdk::Identity>,
    pub gateway: __sdk::__query_builder::Col<MatchConfig, __sdk::Identity>,
    pub capacity: __sdk::__query_builder::Col<MatchConfig, u16>,
    pub away_grace_ticks: __sdk::__query_builder::Col<MatchConfig, u64>,
}

impl __sdk::__query_builder::HasCols for MatchConfig {
    type Cols = MatchConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            gateway: __sdk::__query_builder::Col::new(table_name, "gateway"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            away_grace_ticks: __sdk::__query_builder::Col::new(table_name, "away_grace_ticks"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<MatchConfig, u8>,
}

impl __sdk::__query_builder::HasIxCols for MatchConfig {
    type IxCols = MatchConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchConfigIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchConfig {}
