// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_tick_type::MatchTick;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_tick`.
///
/// Obtain a handle from the [`MatchTickTableAccess::match_tick`] method on [`super::RemoteTables`],
/// like `ctx.db.match_tick()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_tick().on_insert(...)`.
pub struct MatchTickTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchTick>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_tick`.
pub struct MatchTickTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchTickTableAccessor {
    type Row = MatchTick;
    type Handle<'db> = MatchTickTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_tick()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_tick`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchTickTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchTickTableHandle`], which mediates access to the table `match_tick`.
    fn match_tick(&self) -> MatchTickTableHandle<'_>;
}

impl MatchTickTableAccess for super::RemoteTables {
    fn match_tick(&self) -> MatchTickTableHandle<'_> {
        MatchTickTableHandle { imp: self.imp.get_table::<MatchTick>("match_tick"), ctx: std::marker::PhantomData }
    }
}

pub struct MatchTickInsertCallbackId(__sdk::CallbackId);
pub struct MatchTickDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchTickTableHandle<'ctx> {
    type Row = MatchTick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchTick> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchTickTableHandle<'ctx> {
    type Row = MatchTick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchTick> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchTickInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchTickInsertCallbackId {
        MatchTickInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchTickInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchTickDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchTickDeleteCallbackId {
        MatchTickDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchTickDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchTickTableHandle<'ctx> {
    type InsertCallbackId = MatchTickInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchTickInsertCallbackId {
        MatchTickInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchTickInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchTickTableHandle<'ctx> {
    type DeleteCallbackId = MatchTickDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchTickDeleteCallbackId {
        MatchTickDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchTickDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchTickUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchTickTableHandle<'ctx> {
    type UpdateCallbackId = MatchTickUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchTickUpdateCallbackId {
        MatchTickUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchTickUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchTickTableHandle<'ctx> {
    type UpdateCallbackId = MatchTickUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchTickUpdateCallbackId {
        MatchTickUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchTickUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `match_tick`,
/// which allows point queries on the field of the same name
/// via the [`MatchTickIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_tick().id().find(...)`.
pub struct MatchTickIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchTick, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchTickTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `match_tick`.
    pub fn id(&self) -> MatchTickIdUnique<'ctx> {
        MatchTickIdUnique { imp: self.imp.get_unique_constraint::<u8>("id"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> MatchTickIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<MatchTick> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchTick>("match_tick");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<MatchTick>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<MatchTick>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchTick`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_tickQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchTick`.
    fn match_tick(&self) -> __sdk::__query_builder::Table<MatchTick>;
}

impl match_tickQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_tick(&self) -> __sdk::__query_builder::Table<MatchTick> {
        __sdk::__query_builder::Table::new("match_tick")
    }
}
