// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchTick {
    pub id: u8,
    pub tick: u64,
    pub stamped_us: i64,
    pub players: u32,
    pub inputs: u32,
    pub rejected: u32,
    pub rejected_total: u64,
    pub hits: u32,
    pub rejected_hits: u32,
    pub rejected_hits_total: u64,
}

impl __sdk::InModule for MatchTick {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchTick`.
///
/// Provides typed access to columns for query building.
pub struct MatchTickCols {
    pub id: __sdk::__query_builder::Col<MatchTick, u8>,
    pub tick: __sdk::__query_builder::Col<MatchTick, u64>,
    pub stamped_us: __sdk::__query_builder::Col<MatchTick, i64>,
    pub players: __sdk::__query_builder::Col<MatchTick, u32>,
    pub inputs: __sdk::__query_builder::Col<MatchTick, u32>,
    pub rejected: __sdk::__query_builder::Col<MatchTick, u32>,
    pub rejected_total: __sdk::__query_builder::Col<MatchTick, u64>,
    pub hits: __sdk::__query_builder::Col<MatchTick, u32>,
    pub rejected_hits: __sdk::__query_builder::Col<MatchTick, u32>,
    pub rejected_hits_total: __sdk::__query_builder::Col<MatchTick, u64>,
}

impl __sdk::__query_builder::HasCols for MatchTick {
    type Cols = MatchTickCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchTickCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            stamped_us: __sdk::__query_builder::Col::new(table_name, "stamped_us"),
            players: __sdk::__query_builder::Col::new(table_name, "players"),
            inputs: __sdk::__query_builder::Col::new(table_name, "inputs"),
            rejected: __sdk::__query_builder::Col::new(table_name, "rejected"),
            rejected_total: __sdk::__query_builder::Col::new(table_name, "rejected_total"),
            hits: __sdk::__query_builder::Col::new(table_name, "hits"),
            rejected_hits: __sdk::__query_builder::Col::new(table_name, "rejected_hits"),
            rejected_hits_total: __sdk::__query_builder::Col::new(table_name, "rejected_hits_total"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchTick`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchTickIxCols {
    pub id: __sdk::__query_builder::IxCol<MatchTick, u8>,
}

impl __sdk::__query_builder::HasIxCols for MatchTick {
    type IxCols = MatchTickIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchTickIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchTick {}
