// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MemberName {
    pub identity: __sdk::Identity,
    pub name: String,
}

impl __sdk::InModule for MemberName {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MemberName`.
///
/// Provides typed access to columns for query building.
pub struct MemberNameCols {
    pub identity: __sdk::__query_builder::Col<MemberName, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<MemberName, String>,
}

impl __sdk::__query_builder::HasCols for MemberName {
    type Cols = MemberNameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MemberNameCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `MemberName`.
///
/// Provides typed access to indexed columns for query building.
pub struct MemberNameIxCols {
    pub identity: __sdk::__query_builder::IxCol<MemberName, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for MemberName {
    type IxCols = MemberNameIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MemberNameIxCols { identity: __sdk::__query_builder::IxCol::new(table_name, "identity") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MemberName {}
