// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_players_reducer;
pub mod ban_type;
pub mod begin_game_reducer;
pub mod clear_ban_reducer;
pub mod fighter_row_type;
pub mod fighter_table;
pub mod game_state_row_type;
pub mod game_state_table;
pub mod hit_report_row_type;
pub mod input_batch_type;
pub mod item_row_type;
pub mod item_table;
pub mod join_reducer;
pub mod kit_row_type;
pub mod kit_table;
pub mod leave_reducer;
pub mod load_map_reducer;
pub mod map_blob_type;
pub mod map_info_table;
pub mod map_info_type;
pub mod match_config_type;
pub mod match_state_type;
pub mod match_tick_table;
pub mod match_tick_type;
pub mod member_name_type;
pub mod pending_death_type;
pub mod player_row_type;
pub mod player_table;
pub mod powerup_row_type;
pub mod powerup_table;
pub mod remove_players_reducer;
pub mod report_ammo_reducer;
pub mod report_death_reducer;
pub mod report_hits_reducer;
pub mod reset_reducer;
pub mod roster_row_type;
pub mod roster_table;
pub mod seat_table;
pub mod seat_type;
pub mod set_away_grace_reducer;
pub mod set_ban_reducer;
pub mod set_capacity_reducer;
pub mod set_game_reducer;
pub mod set_gateway_reducer;
pub mod set_loadout_reducer;
pub mod set_name_reducer;
pub mod set_spawn_points_reducer;
pub mod set_variant_reducer;
pub mod shooter_row_type;
pub mod spawn_point_type;
pub mod standing_row_type;
pub mod standing_table;
pub mod start_reducer;
pub mod stop_reducer;
pub mod submit_inputs_reducer;
pub mod tick_timer_type;
pub mod use_item_reducer;
pub mod use_request_type;

pub use add_players_reducer::add_players;
pub use ban_type::Ban;
pub use begin_game_reducer::begin_game;
pub use clear_ban_reducer::clear_ban;
pub use fighter_row_type::FighterRow;
pub use fighter_table::*;
pub use game_state_row_type::GameStateRow;
pub use game_state_table::*;
pub use hit_report_row_type::HitReportRow;
pub use input_batch_type::InputBatch;
pub use item_row_type::ItemRow;
pub use item_table::*;
pub use join_reducer::join;
pub use kit_row_type::KitRow;
pub use kit_table::*;
pub use leave_reducer::leave;
pub use load_map_reducer::load_map;
pub use map_blob_type::MapBlob;
pub use map_info_table::*;
pub use map_info_type::MapInfo;
pub use match_config_type::MatchConfig;
pub use match_state_type::MatchState;
pub use match_tick_table::*;
pub use match_tick_type::MatchTick;
pub use member_name_type::MemberName;
pub use pending_death_type::PendingDeath;
pub use player_row_type::PlayerRow;
pub use player_table::*;
pub use powerup_row_type::PowerupRow;
pub use powerup_table::*;
pub use remove_players_reducer::remove_players;
pub use report_ammo_reducer::report_ammo;
pub use report_death_reducer::report_death;
pub use report_hits_reducer::report_hits;
pub use reset_reducer::reset;
pub use roster_row_type::RosterRow;
pub use roster_table::*;
pub use seat_table::*;
pub use seat_type::Seat;
pub use set_away_grace_reducer::set_away_grace;
pub use set_ban_reducer::set_ban;
pub use set_capacity_reducer::set_capacity;
pub use set_game_reducer::set_game;
pub use set_gateway_reducer::set_gateway;
pub use set_loadout_reducer::set_loadout;
pub use set_name_reducer::set_name;
pub use set_spawn_points_reducer::set_spawn_points;
pub use set_variant_reducer::set_variant;
pub use shooter_row_type::ShooterRow;
pub use spawn_point_type::SpawnPoint;
pub use standing_row_type::StandingRow;
pub use standing_table::*;
pub use start_reducer::start;
pub use stop_reducer::stop;
pub use submit_inputs_reducer::submit_inputs;
pub use tick_timer_type::TickTimer;
pub use use_item_reducer::use_item;
pub use use_request_type::UseRequest;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddPlayers {
        batch: Vec<u8>,
    },
    BeginGame,
    ClearBan {
        identity: __sdk::Identity,
    },
    Join {
        udp_key: Vec<u8>,
    },
    Leave,
    LoadMap {
        data: Vec<u8>,
    },
    RemovePlayers {
        ids: Vec<u16>,
    },
    ReportAmmo {
        rounds: Vec<u8>,
    },
    ReportDeath {
        victim: u16,
        killer: u16,
    },
    ReportHits {
        batch: Vec<u8>,
    },
    Reset,
    SetAwayGrace {
        ticks: u64,
    },
    SetBan {
        identity: __sdk::Identity,
        reason: String,
    },
    SetCapacity {
        capacity: u16,
    },
    SetGame {
        teams: bool,
        score_limit: u32,
        time_limit_ticks: u32,
        respawn_ticks: u32,
        respawn_growth_ticks: u32,
        suicide_penalty_ticks: u32,
        wave_ticks: u32,
    },
    SetGateway {
        gateway: __sdk::Identity,
    },
    SetLoadout {
        player: u16,
        weapon_0: u16,
        weapon_1: u16,
    },
    SetName {
        identity: __sdk::Identity,
        name: String,
    },
    SetSpawnPoints {
        batch: Vec<u8>,
    },
    SetVariant {
        weapon_set: u8,
        map_equipment: bool,
        infinite_grenades: bool,
    },
    Start,
    Stop,
    SubmitInputs {
        batch: Vec<u8>,
    },
    UseItem {
        slot: u8,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddPlayers { .. } => "add_players",
            Reducer::BeginGame => "begin_game",
            Reducer::ClearBan { .. } => "clear_ban",
            Reducer::Join { .. } => "join",
            Reducer::Leave => "leave",
            Reducer::LoadMap { .. } => "load_map",
            Reducer::RemovePlayers { .. } => "remove_players",
            Reducer::ReportAmmo { .. } => "report_ammo",
            Reducer::ReportDeath { .. } => "report_death",
            Reducer::ReportHits { .. } => "report_hits",
            Reducer::Reset => "reset",
            Reducer::SetAwayGrace { .. } => "set_away_grace",
            Reducer::SetBan { .. } => "set_ban",
            Reducer::SetCapacity { .. } => "set_capacity",
            Reducer::SetGame { .. } => "set_game",
            Reducer::SetGateway { .. } => "set_gateway",
            Reducer::SetLoadout { .. } => "set_loadout",
            Reducer::SetName { .. } => "set_name",
            Reducer::SetSpawnPoints { .. } => "set_spawn_points",
            Reducer::SetVariant { .. } => "set_variant",
            Reducer::Start => "start",
            Reducer::Stop => "stop",
            Reducer::SubmitInputs { .. } => "submit_inputs",
            Reducer::UseItem { .. } => "use_item",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AddPlayers { batch } => {
                __sats::bsatn::to_vec(&add_players_reducer::AddPlayersArgs { batch: batch.clone() })
            }
            Reducer::BeginGame => __sats::bsatn::to_vec(&begin_game_reducer::BeginGameArgs {}),
            Reducer::ClearBan { identity } => {
                __sats::bsatn::to_vec(&clear_ban_reducer::ClearBanArgs { identity: identity.clone() })
            }
            Reducer::Join { udp_key } => __sats::bsatn::to_vec(&join_reducer::JoinArgs { udp_key: udp_key.clone() }),
            Reducer::Leave => __sats::bsatn::to_vec(&leave_reducer::LeaveArgs {}),
            Reducer::LoadMap { data } => __sats::bsatn::to_vec(&load_map_reducer::LoadMapArgs { data: data.clone() }),
            Reducer::RemovePlayers { ids } => {
                __sats::bsatn::to_vec(&remove_players_reducer::RemovePlayersArgs { ids: ids.clone() })
            }
            Reducer::ReportAmmo { rounds } => {
                __sats::bsatn::to_vec(&report_ammo_reducer::ReportAmmoArgs { rounds: rounds.clone() })
            }
            Reducer::ReportDeath { victim, killer } => __sats::bsatn::to_vec(&report_death_reducer::ReportDeathArgs {
                victim: victim.clone(),
                killer: killer.clone(),
            }),
            Reducer::ReportHits { batch } => {
                __sats::bsatn::to_vec(&report_hits_reducer::ReportHitsArgs { batch: batch.clone() })
            }
            Reducer::Reset => __sats::bsatn::to_vec(&reset_reducer::ResetArgs {}),
            Reducer::SetAwayGrace { ticks } => {
                __sats::bsatn::to_vec(&set_away_grace_reducer::SetAwayGraceArgs { ticks: ticks.clone() })
            }
            Reducer::SetBan { identity, reason } => __sats::bsatn::to_vec(&set_ban_reducer::SetBanArgs {
                identity: identity.clone(),
                reason: reason.clone(),
            }),
            Reducer::SetCapacity { capacity } => {
                __sats::bsatn::to_vec(&set_capacity_reducer::SetCapacityArgs { capacity: capacity.clone() })
            }
            Reducer::SetGame {
                teams,
                score_limit,
                time_limit_ticks,
                respawn_ticks,
                respawn_growth_ticks,
                suicide_penalty_ticks,
                wave_ticks,
            } => __sats::bsatn::to_vec(&set_game_reducer::SetGameArgs {
                teams: teams.clone(),
                score_limit: score_limit.clone(),
                time_limit_ticks: time_limit_ticks.clone(),
                respawn_ticks: respawn_ticks.clone(),
                respawn_growth_ticks: respawn_growth_ticks.clone(),
                suicide_penalty_ticks: suicide_penalty_ticks.clone(),
                wave_ticks: wave_ticks.clone(),
            }),
            Reducer::SetGateway { gateway } => {
                __sats::bsatn::to_vec(&set_gateway_reducer::SetGatewayArgs { gateway: gateway.clone() })
            }
            Reducer::SetLoadout { player, weapon_0, weapon_1 } => {
                __sats::bsatn::to_vec(&set_loadout_reducer::SetLoadoutArgs {
                    player: player.clone(),
                    weapon_0: weapon_0.clone(),
                    weapon_1: weapon_1.clone(),
                })
            }
            Reducer::SetName { identity, name } => {
                __sats::bsatn::to_vec(&set_name_reducer::SetNameArgs { identity: identity.clone(), name: name.clone() })
            }
            Reducer::SetSpawnPoints { batch } => {
                __sats::bsatn::to_vec(&set_spawn_points_reducer::SetSpawnPointsArgs { batch: batch.clone() })
            }
            Reducer::SetVariant { weapon_set, map_equipment, infinite_grenades } => {
                __sats::bsatn::to_vec(&set_variant_reducer::SetVariantArgs {
                    weapon_set: weapon_set.clone(),
                    map_equipment: map_equipment.clone(),
                    infinite_grenades: infinite_grenades.clone(),
                })
            }
            Reducer::Start => __sats::bsatn::to_vec(&start_reducer::StartArgs {}),
            Reducer::Stop => __sats::bsatn::to_vec(&stop_reducer::StopArgs {}),
            Reducer::SubmitInputs { batch } => {
                __sats::bsatn::to_vec(&submit_inputs_reducer::SubmitInputsArgs { batch: batch.clone() })
            }
            Reducer::UseItem { slot } => __sats::bsatn::to_vec(&use_item_reducer::UseItemArgs { slot: slot.clone() }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    fighter: __sdk::TableUpdate<FighterRow>,
    game_state: __sdk::TableUpdate<GameStateRow>,
    item: __sdk::TableUpdate<ItemRow>,
    kit: __sdk::TableUpdate<KitRow>,
    map_info: __sdk::TableUpdate<MapInfo>,
    match_tick: __sdk::TableUpdate<MatchTick>,
    player: __sdk::TableUpdate<PlayerRow>,
    powerup: __sdk::TableUpdate<PowerupRow>,
    roster: __sdk::TableUpdate<RosterRow>,
    seat: __sdk::TableUpdate<Seat>,
    standing: __sdk::TableUpdate<StandingRow>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "fighter" => db_update.fighter.append(fighter_table::parse_table_update(table_update)?),
                "game_state" => db_update.game_state.append(game_state_table::parse_table_update(table_update)?),
                "item" => db_update.item.append(item_table::parse_table_update(table_update)?),
                "kit" => db_update.kit.append(kit_table::parse_table_update(table_update)?),
                "map_info" => db_update.map_info.append(map_info_table::parse_table_update(table_update)?),
                "match_tick" => db_update.match_tick.append(match_tick_table::parse_table_update(table_update)?),
                "player" => db_update.player.append(player_table::parse_table_update(table_update)?),
                "powerup" => db_update.powerup.append(powerup_table::parse_table_update(table_update)?),
                "roster" => db_update.roster.append(roster_table::parse_table_update(table_update)?),
                "seat" => db_update.seat.append(seat_table::parse_table_update(table_update)?),
                "standing" => db_update.standing.append(standing_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name("table", unknown, "DatabaseUpdate").into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.fighter =
            cache.apply_diff_to_table::<FighterRow>("fighter", &self.fighter).with_updates_by_pk(|row| &row.player);
        diff.game_state =
            cache.apply_diff_to_table::<GameStateRow>("game_state", &self.game_state).with_updates_by_pk(|row| &row.id);
        diff.item = cache.apply_diff_to_table::<ItemRow>("item", &self.item).with_updates_by_pk(|row| &row.id);
        diff.kit = cache.apply_diff_to_table::<KitRow>("kit", &self.kit).with_updates_by_pk(|row| &row.player);
        diff.map_info =
            cache.apply_diff_to_table::<MapInfo>("map_info", &self.map_info).with_updates_by_pk(|row| &row.id);
        diff.match_tick =
            cache.apply_diff_to_table::<MatchTick>("match_tick", &self.match_tick).with_updates_by_pk(|row| &row.id);
        diff.player = cache.apply_diff_to_table::<PlayerRow>("player", &self.player).with_updates_by_pk(|row| &row.id);
        diff.powerup =
            cache.apply_diff_to_table::<PowerupRow>("powerup", &self.powerup).with_updates_by_pk(|row| &row.player);
        diff.roster =
            cache.apply_diff_to_table::<RosterRow>("roster", &self.roster).with_updates_by_pk(|row| &row.player);
        diff.seat = cache.apply_diff_to_table::<Seat>("seat", &self.seat).with_updates_by_pk(|row| &row.player);
        diff.standing =
            cache.apply_diff_to_table::<StandingRow>("standing", &self.standing).with_updates_by_pk(|row| &row.player);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "fighter" => db_update.fighter.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_state" => db_update.game_state.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "item" => db_update.item.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "kit" => db_update.kit.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "map_info" => db_update.map_info.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_tick" => db_update.match_tick.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update.player.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "powerup" => db_update.powerup.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "roster" => db_update.roster.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "seat" => db_update.seat.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "standing" => db_update.standing.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into());
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "fighter" => db_update.fighter.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_state" => db_update.game_state.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "item" => db_update.item.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "kit" => db_update.kit.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "map_info" => db_update.map_info.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_tick" => db_update.match_tick.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update.player.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "powerup" => db_update.powerup.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "roster" => db_update.roster.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "seat" => db_update.seat.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "standing" => db_update.standing.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into());
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    fighter: __sdk::TableAppliedDiff<'r, FighterRow>,
    game_state: __sdk::TableAppliedDiff<'r, GameStateRow>,
    item: __sdk::TableAppliedDiff<'r, ItemRow>,
    kit: __sdk::TableAppliedDiff<'r, KitRow>,
    map_info: __sdk::TableAppliedDiff<'r, MapInfo>,
    match_tick: __sdk::TableAppliedDiff<'r, MatchTick>,
    player: __sdk::TableAppliedDiff<'r, PlayerRow>,
    powerup: __sdk::TableAppliedDiff<'r, PowerupRow>,
    roster: __sdk::TableAppliedDiff<'r, RosterRow>,
    seat: __sdk::TableAppliedDiff<'r, Seat>,
    standing: __sdk::TableAppliedDiff<'r, StandingRow>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
        callbacks.invoke_table_row_callbacks::<FighterRow>("fighter", &self.fighter, event);
        callbacks.invoke_table_row_callbacks::<GameStateRow>("game_state", &self.game_state, event);
        callbacks.invoke_table_row_callbacks::<ItemRow>("item", &self.item, event);
        callbacks.invoke_table_row_callbacks::<KitRow>("kit", &self.kit, event);
        callbacks.invoke_table_row_callbacks::<MapInfo>("map_info", &self.map_info, event);
        callbacks.invoke_table_row_callbacks::<MatchTick>("match_tick", &self.match_tick, event);
        callbacks.invoke_table_row_callbacks::<PlayerRow>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PowerupRow>("powerup", &self.powerup, event);
        callbacks.invoke_table_row_callbacks::<RosterRow>("roster", &self.roster, event);
        callbacks.invoke_table_row_callbacks::<Seat>("seat", &self.seat, event);
        callbacks.invoke_table_row_callbacks::<StandingRow>("standing", &self.standing, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        fighter_table::register_table(client_cache);
        game_state_table::register_table(client_cache);
        item_table::register_table(client_cache);
        kit_table::register_table(client_cache);
        map_info_table::register_table(client_cache);
        match_tick_table::register_table(client_cache);
        player_table::register_table(client_cache);
        powerup_table::register_table(client_cache);
        roster_table::register_table(client_cache);
        seat_table::register_table(client_cache);
        standing_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "fighter",
        "game_state",
        "item",
        "kit",
        "map_info",
        "match_tick",
        "player",
        "powerup",
        "roster",
        "seat",
        "standing",
    ];
}
