// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PendingDeath {
    pub id: u64,
    pub victim: u16,
    pub killer: u16,
}

impl __sdk::InModule for PendingDeath {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PendingDeath`.
///
/// Provides typed access to columns for query building.
pub struct PendingDeathCols {
    pub id: __sdk::__query_builder::Col<PendingDeath, u64>,
    pub victim: __sdk::__query_builder::Col<PendingDeath, u16>,
    pub killer: __sdk::__query_builder::Col<PendingDeath, u16>,
}

impl __sdk::__query_builder::HasCols for PendingDeath {
    type Cols = PendingDeathCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PendingDeathCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            victim: __sdk::__query_builder::Col::new(table_name, "victim"),
            killer: __sdk::__query_builder::Col::new(table_name, "killer"),
        }
    }
}

/// Indexed column accessor struct for the table `PendingDeath`.
///
/// Provides typed access to indexed columns for query building.
pub struct PendingDeathIxCols {
    pub id: __sdk::__query_builder::IxCol<PendingDeath, u64>,
}

impl __sdk::__query_builder::HasIxCols for PendingDeath {
    type IxCols = PendingDeathIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PendingDeathIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PendingDeath {}
