// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerRow {
    pub id: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub pitch: f32,
    pub updated_tick: u64,
    pub rejected_moves: u64,
    pub last_reject: u8,
    pub last_reject_tick: u64,
}

impl __sdk::InModule for PlayerRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerRow`.
///
/// Provides typed access to columns for query building.
pub struct PlayerRowCols {
    pub id: __sdk::__query_builder::Col<PlayerRow, u16>,
    pub x: __sdk::__query_builder::Col<PlayerRow, f32>,
    pub y: __sdk::__query_builder::Col<PlayerRow, f32>,
    pub z: __sdk::__query_builder::Col<PlayerRow, f32>,
    pub yaw: __sdk::__query_builder::Col<PlayerRow, f32>,
    pub pitch: __sdk::__query_builder::Col<PlayerRow, f32>,
    pub updated_tick: __sdk::__query_builder::Col<PlayerRow, u64>,
    pub rejected_moves: __sdk::__query_builder::Col<PlayerRow, u64>,
    pub last_reject: __sdk::__query_builder::Col<PlayerRow, u8>,
    pub last_reject_tick: __sdk::__query_builder::Col<PlayerRow, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerRow {
    type Cols = PlayerRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
            updated_tick: __sdk::__query_builder::Col::new(table_name, "updated_tick"),
            rejected_moves: __sdk::__query_builder::Col::new(table_name, "rejected_moves"),
            last_reject: __sdk::__query_builder::Col::new(table_name, "last_reject"),
            last_reject_tick: __sdk::__query_builder::Col::new(table_name, "last_reject_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerRowIxCols {
    pub id: __sdk::__query_builder::IxCol<PlayerRow, u16>,
}

impl __sdk::__query_builder::HasIxCols for PlayerRow {
    type IxCols = PlayerRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerRowIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerRow {}
