// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PowerupRow {
    pub player: u16,
    pub camo_until: u64,
}

impl __sdk::InModule for PowerupRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PowerupRow`.
///
/// Provides typed access to columns for query building.
pub struct PowerupRowCols {
    pub player: __sdk::__query_builder::Col<PowerupRow, u16>,
    pub camo_until: __sdk::__query_builder::Col<PowerupRow, u64>,
}

impl __sdk::__query_builder::HasCols for PowerupRow {
    type Cols = PowerupRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PowerupRowCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            camo_until: __sdk::__query_builder::Col::new(table_name, "camo_until"),
        }
    }
}

/// Indexed column accessor struct for the table `PowerupRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PowerupRowIxCols {
    pub player: __sdk::__query_builder::IxCol<PowerupRow, u16>,
}

impl __sdk::__query_builder::HasIxCols for PowerupRow {
    type IxCols = PowerupRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PowerupRowIxCols { player: __sdk::__query_builder::IxCol::new(table_name, "player") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PowerupRow {}
