// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::powerup_row_type::PowerupRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `powerup`.
///
/// Obtain a handle from the [`PowerupTableAccess::powerup`] method on [`super::RemoteTables`],
/// like `ctx.db.powerup()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.powerup().on_insert(...)`.
pub struct PowerupTableHandle<'ctx> {
    imp: __sdk::TableHandle<PowerupRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `powerup`.
pub struct PowerupTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PowerupTableAccessor {
    type Row = PowerupRow;
    type Handle<'db> = PowerupTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.powerup()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `powerup`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PowerupTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PowerupTableHandle`], which mediates access to the table `powerup`.
    fn powerup(&self) -> PowerupTableHandle<'_>;
}

impl PowerupTableAccess for super::RemoteTables {
    fn powerup(&self) -> PowerupTableHandle<'_> {
        PowerupTableHandle { imp: self.imp.get_table::<PowerupRow>("powerup"), ctx: std::marker::PhantomData }
    }
}

pub struct PowerupInsertCallbackId(__sdk::CallbackId);
pub struct PowerupDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PowerupTableHandle<'ctx> {
    type Row = PowerupRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PowerupRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PowerupTableHandle<'ctx> {
    type Row = PowerupRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PowerupRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PowerupInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PowerupInsertCallbackId {
        PowerupInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PowerupInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PowerupDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PowerupDeleteCallbackId {
        PowerupDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PowerupDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PowerupTableHandle<'ctx> {
    type InsertCallbackId = PowerupInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PowerupInsertCallbackId {
        PowerupInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PowerupInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PowerupTableHandle<'ctx> {
    type DeleteCallbackId = PowerupDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PowerupDeleteCallbackId {
        PowerupDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PowerupDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PowerupUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PowerupTableHandle<'ctx> {
    type UpdateCallbackId = PowerupUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PowerupUpdateCallbackId {
        PowerupUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PowerupUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PowerupTableHandle<'ctx> {
    type UpdateCallbackId = PowerupUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PowerupUpdateCallbackId {
        PowerupUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PowerupUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player` unique index on the table `powerup`,
/// which allows point queries on the field of the same name
/// via the [`PowerupPlayerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.powerup().player().find(...)`.
pub struct PowerupPlayerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PowerupRow, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PowerupTableHandle<'ctx> {
    /// Get a handle on the `player` unique index on the table `powerup`.
    pub fn player(&self) -> PowerupPlayerUnique<'ctx> {
        PowerupPlayerUnique { imp: self.imp.get_unique_constraint::<u16>("player"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> PowerupPlayerUnique<'ctx> {
    /// Find the subscribed row whose `player` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<PowerupRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PowerupRow>("powerup");
    _table.add_unique_constraint::<u16>("player", |row| &row.player);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<PowerupRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<PowerupRow>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PowerupRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait powerupQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PowerupRow`.
    fn powerup(&self) -> __sdk::__query_builder::Table<PowerupRow>;
}

impl powerupQueryTableAccess for __sdk::QueryTableAccessor {
    fn powerup(&self) -> __sdk::__query_builder::Table<PowerupRow> {
        __sdk::__query_builder::Table::new("powerup")
    }
}
