// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportAmmoArgs {
    pub rounds: Vec<u8>,
}

impl From<ReportAmmoArgs> for super::Reducer {
    fn from(args: ReportAmmoArgs) -> Self {
        Self::ReportAmmo { rounds: args.rounds }
    }
}

impl __sdk::InModule for ReportAmmoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_ammo`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_ammo {
    /// Request that the remote module invoke the reducer `report_ammo` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_ammo:report_ammo_then`] to run a callback after the reducer completes.
    fn report_ammo(&self, rounds: Vec<u8>) -> __sdk::Result<()> {
        self.report_ammo_then(rounds, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `report_ammo` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_ammo_then(
        &self,
        rounds: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl report_ammo for super::RemoteReducers {
    fn report_ammo_then(
        &self,
        rounds: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ReportAmmoArgs { rounds }, callback)
    }
}
