// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportHitsArgs {
    pub batch: Vec<u8>,
}

impl From<ReportHitsArgs> for super::Reducer {
    fn from(args: ReportHitsArgs) -> Self {
        Self::ReportHits { batch: args.batch }
    }
}

impl __sdk::InModule for ReportHitsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_hits`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_hits {
    /// Request that the remote module invoke the reducer `report_hits` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_hits:report_hits_then`] to run a callback after the reducer completes.
    fn report_hits(&self, batch: Vec<u8>) -> __sdk::Result<()> {
        self.report_hits_then(batch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `report_hits` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_hits_then(
        &self,
        batch: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl report_hits for super::RemoteReducers {
    fn report_hits_then(
        &self,
        batch: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ReportHitsArgs { batch }, callback)
    }
}
