// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RosterRow {
    pub player: u16,
    pub team: u8,
    pub name: String,
}

impl __sdk::InModule for RosterRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RosterRow`.
///
/// Provides typed access to columns for query building.
pub struct RosterRowCols {
    pub player: __sdk::__query_builder::Col<RosterRow, u16>,
    pub team: __sdk::__query_builder::Col<RosterRow, u8>,
    pub name: __sdk::__query_builder::Col<RosterRow, String>,
}

impl __sdk::__query_builder::HasCols for RosterRow {
    type Cols = RosterRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RosterRowCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            team: __sdk::__query_builder::Col::new(table_name, "team"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `RosterRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct RosterRowIxCols {
    pub player: __sdk::__query_builder::IxCol<RosterRow, u16>,
}

impl __sdk::__query_builder::HasIxCols for RosterRow {
    type IxCols = RosterRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RosterRowIxCols { player: __sdk::__query_builder::IxCol::new(table_name, "player") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RosterRow {}
