// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::roster_row_type::RosterRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `roster`.
///
/// Obtain a handle from the [`RosterTableAccess::roster`] method on [`super::RemoteTables`],
/// like `ctx.db.roster()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.roster().on_insert(...)`.
pub struct RosterTableHandle<'ctx> {
    imp: __sdk::TableHandle<RosterRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `roster`.
pub struct RosterTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RosterTableAccessor {
    type Row = RosterRow;
    type Handle<'db> = RosterTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.roster()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `roster`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RosterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RosterTableHandle`], which mediates access to the table `roster`.
    fn roster(&self) -> RosterTableHandle<'_>;
}

impl RosterTableAccess for super::RemoteTables {
    fn roster(&self) -> RosterTableHandle<'_> {
        RosterTableHandle { imp: self.imp.get_table::<RosterRow>("roster"), ctx: std::marker::PhantomData }
    }
}

pub struct RosterInsertCallbackId(__sdk::CallbackId);
pub struct RosterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RosterTableHandle<'ctx> {
    type Row = RosterRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RosterRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RosterTableHandle<'ctx> {
    type Row = RosterRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RosterRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RosterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RosterInsertCallbackId {
        RosterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RosterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RosterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RosterDeleteCallbackId {
        RosterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RosterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RosterTableHandle<'ctx> {
    type InsertCallbackId = RosterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RosterInsertCallbackId {
        RosterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RosterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RosterTableHandle<'ctx> {
    type DeleteCallbackId = RosterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RosterDeleteCallbackId {
        RosterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RosterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RosterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RosterTableHandle<'ctx> {
    type UpdateCallbackId = RosterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RosterUpdateCallbackId {
        RosterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RosterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RosterTableHandle<'ctx> {
    type UpdateCallbackId = RosterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RosterUpdateCallbackId {
        RosterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RosterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player` unique index on the table `roster`,
/// which allows point queries on the field of the same name
/// via the [`RosterPlayerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.roster().player().find(...)`.
pub struct RosterPlayerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RosterRow, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RosterTableHandle<'ctx> {
    /// Get a handle on the `player` unique index on the table `roster`.
    pub fn player(&self) -> RosterPlayerUnique<'ctx> {
        RosterPlayerUnique { imp: self.imp.get_unique_constraint::<u16>("player"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> RosterPlayerUnique<'ctx> {
    /// Find the subscribed row whose `player` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<RosterRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RosterRow>("roster");
    _table.add_unique_constraint::<u16>("player", |row| &row.player);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<RosterRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<RosterRow>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RosterRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait rosterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RosterRow`.
    fn roster(&self) -> __sdk::__query_builder::Table<RosterRow>;
}

impl rosterQueryTableAccess for __sdk::QueryTableAccessor {
    fn roster(&self) -> __sdk::__query_builder::Table<RosterRow> {
        __sdk::__query_builder::Table::new("roster")
    }
}
