// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Seat {
    pub player: u16,
    pub owner: __sdk::Identity,
    pub udp_key: Vec<u8>,
    pub connection: Option<__sdk::ConnectionId>,
    pub away_since: u64,
}

impl __sdk::InModule for Seat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Seat`.
///
/// Provides typed access to columns for query building.
pub struct SeatCols {
    pub player: __sdk::__query_builder::Col<Seat, u16>,
    pub owner: __sdk::__query_builder::Col<Seat, __sdk::Identity>,
    pub udp_key: __sdk::__query_builder::Col<Seat, Vec<u8>>,
    pub connection: __sdk::__query_builder::Col<Seat, Option<__sdk::ConnectionId>>,
    pub away_since: __sdk::__query_builder::Col<Seat, u64>,
}

impl __sdk::__query_builder::HasCols for Seat {
    type Cols = SeatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SeatCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            udp_key: __sdk::__query_builder::Col::new(table_name, "udp_key"),
            connection: __sdk::__query_builder::Col::new(table_name, "connection"),
            away_since: __sdk::__query_builder::Col::new(table_name, "away_since"),
        }
    }
}

/// Indexed column accessor struct for the table `Seat`.
///
/// Provides typed access to indexed columns for query building.
pub struct SeatIxCols {
    pub owner: __sdk::__query_builder::IxCol<Seat, __sdk::Identity>,
    pub player: __sdk::__query_builder::IxCol<Seat, u16>,
}

impl __sdk::__query_builder::HasIxCols for Seat {
    type IxCols = SeatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SeatIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            player: __sdk::__query_builder::IxCol::new(table_name, "player"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Seat {}
