// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetGameArgs {
    pub teams: bool,
    pub score_limit: u32,
    pub time_limit_ticks: u32,
    pub respawn_ticks: u32,
    pub respawn_growth_ticks: u32,
    pub suicide_penalty_ticks: u32,
    pub wave_ticks: u32,
}

impl From<SetGameArgs> for super::Reducer {
    fn from(args: SetGameArgs) -> Self {
        Self::SetGame {
            teams: args.teams,
            score_limit: args.score_limit,
            time_limit_ticks: args.time_limit_ticks,
            respawn_ticks: args.respawn_ticks,
            respawn_growth_ticks: args.respawn_growth_ticks,
            suicide_penalty_ticks: args.suicide_penalty_ticks,
            wave_ticks: args.wave_ticks,
        }
    }
}

impl __sdk::InModule for SetGameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_game {
    /// Request that the remote module invoke the reducer `set_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_game:set_game_then`] to run a callback after the reducer completes.
    fn set_game(
        &self,
        teams: bool,
        score_limit: u32,
        time_limit_ticks: u32,
        respawn_ticks: u32,
        respawn_growth_ticks: u32,
        suicide_penalty_ticks: u32,
        wave_ticks: u32,
    ) -> __sdk::Result<()> {
        self.set_game_then(
            teams,
            score_limit,
            time_limit_ticks,
            respawn_ticks,
            respawn_growth_ticks,
            suicide_penalty_ticks,
            wave_ticks,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_game` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_game_then(
        &self,
        teams: bool,
        score_limit: u32,
        time_limit_ticks: u32,
        respawn_ticks: u32,
        respawn_growth_ticks: u32,
        suicide_penalty_ticks: u32,
        wave_ticks: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_game for super::RemoteReducers {
    fn set_game_then(
        &self,
        teams: bool,
        score_limit: u32,
        time_limit_ticks: u32,
        respawn_ticks: u32,
        respawn_growth_ticks: u32,
        suicide_penalty_ticks: u32,
        wave_ticks: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetGameArgs {
                teams,
                score_limit,
                time_limit_ticks,
                respawn_ticks,
                respawn_growth_ticks,
                suicide_penalty_ticks,
                wave_ticks,
            },
            callback,
        )
    }
}
