// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSpawnPointsArgs {
    pub batch: Vec<u8>,
}

impl From<SetSpawnPointsArgs> for super::Reducer {
    fn from(args: SetSpawnPointsArgs) -> Self {
        Self::SetSpawnPoints { batch: args.batch }
    }
}

impl __sdk::InModule for SetSpawnPointsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_spawn_points`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_spawn_points {
    /// Request that the remote module invoke the reducer `set_spawn_points` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_spawn_points:set_spawn_points_then`] to run a callback after the reducer completes.
    fn set_spawn_points(&self, batch: Vec<u8>) -> __sdk::Result<()> {
        self.set_spawn_points_then(batch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_spawn_points` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_spawn_points_then(
        &self,
        batch: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_spawn_points for super::RemoteReducers {
    fn set_spawn_points_then(
        &self,
        batch: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetSpawnPointsArgs { batch }, callback)
    }
}
