// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetVariantArgs {
    pub weapon_set: u8,
    pub map_equipment: bool,
    pub infinite_grenades: bool,
}

impl From<SetVariantArgs> for super::Reducer {
    fn from(args: SetVariantArgs) -> Self {
        Self::SetVariant {
            weapon_set: args.weapon_set,
            map_equipment: args.map_equipment,
            infinite_grenades: args.infinite_grenades,
        }
    }
}

impl __sdk::InModule for SetVariantArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_variant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_variant {
    /// Request that the remote module invoke the reducer `set_variant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_variant:set_variant_then`] to run a callback after the reducer completes.
    fn set_variant(&self, weapon_set: u8, map_equipment: bool, infinite_grenades: bool) -> __sdk::Result<()> {
        self.set_variant_then(weapon_set, map_equipment, infinite_grenades, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_variant` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_variant_then(
        &self,
        weapon_set: u8,
        map_equipment: bool,
        infinite_grenades: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_variant for super::RemoteReducers {
    fn set_variant_then(
        &self,
        weapon_set: u8,
        map_equipment: bool,
        infinite_grenades: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetVariantArgs { weapon_set, map_equipment, infinite_grenades }, callback)
    }
}
