// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShooterRow {
    pub player: u16,
    pub hit_seconds: f32,
    pub hit_seconds_tick: u64,
    pub accepted: u64,
    pub rejected: u64,
    pub last_reject: u8,
    pub last_reject_tick: u64,
}

impl __sdk::InModule for ShooterRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShooterRow`.
///
/// Provides typed access to columns for query building.
pub struct ShooterRowCols {
    pub player: __sdk::__query_builder::Col<ShooterRow, u16>,
    pub hit_seconds: __sdk::__query_builder::Col<ShooterRow, f32>,
    pub hit_seconds_tick: __sdk::__query_builder::Col<ShooterRow, u64>,
    pub accepted: __sdk::__query_builder::Col<ShooterRow, u64>,
    pub rejected: __sdk::__query_builder::Col<ShooterRow, u64>,
    pub last_reject: __sdk::__query_builder::Col<ShooterRow, u8>,
    pub last_reject_tick: __sdk::__query_builder::Col<ShooterRow, u64>,
}

impl __sdk::__query_builder::HasCols for ShooterRow {
    type Cols = ShooterRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShooterRowCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            hit_seconds: __sdk::__query_builder::Col::new(table_name, "hit_seconds"),
            hit_seconds_tick: __sdk::__query_builder::Col::new(table_name, "hit_seconds_tick"),
            accepted: __sdk::__query_builder::Col::new(table_name, "accepted"),
            rejected: __sdk::__query_builder::Col::new(table_name, "rejected"),
            last_reject: __sdk::__query_builder::Col::new(table_name, "last_reject"),
            last_reject_tick: __sdk::__query_builder::Col::new(table_name, "last_reject_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `ShooterRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShooterRowIxCols {
    pub player: __sdk::__query_builder::IxCol<ShooterRow, u16>,
}

impl __sdk::__query_builder::HasIxCols for ShooterRow {
    type IxCols = ShooterRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShooterRowIxCols { player: __sdk::__query_builder::IxCol::new(table_name, "player") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShooterRow {}
