// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpawnPoint {
    pub index: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
}

impl __sdk::InModule for SpawnPoint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpawnPoint`.
///
/// Provides typed access to columns for query building.
pub struct SpawnPointCols {
    pub index: __sdk::__query_builder::Col<SpawnPoint, u32>,
    pub x: __sdk::__query_builder::Col<SpawnPoint, f32>,
    pub y: __sdk::__query_builder::Col<SpawnPoint, f32>,
    pub z: __sdk::__query_builder::Col<SpawnPoint, f32>,
    pub yaw: __sdk::__query_builder::Col<SpawnPoint, f32>,
}

impl __sdk::__query_builder::HasCols for SpawnPoint {
    type Cols = SpawnPointCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpawnPointCols {
            index: __sdk::__query_builder::Col::new(table_name, "index"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
        }
    }
}

/// Indexed column accessor struct for the table `SpawnPoint`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpawnPointIxCols {
    pub index: __sdk::__query_builder::IxCol<SpawnPoint, u32>,
}

impl __sdk::__query_builder::HasIxCols for SpawnPoint {
    type IxCols = SpawnPointIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpawnPointIxCols { index: __sdk::__query_builder::IxCol::new(table_name, "index") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpawnPoint {}
