// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::standing_row_type::StandingRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `standing`.
///
/// Obtain a handle from the [`StandingTableAccess::standing`] method on [`super::RemoteTables`],
/// like `ctx.db.standing()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.standing().on_insert(...)`.
pub struct StandingTableHandle<'ctx> {
    imp: __sdk::TableHandle<StandingRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `standing`.
pub struct StandingTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StandingTableAccessor {
    type Row = StandingRow;
    type Handle<'db> = StandingTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.standing()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `standing`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StandingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StandingTableHandle`], which mediates access to the table `standing`.
    fn standing(&self) -> StandingTableHandle<'_>;
}

impl StandingTableAccess for super::RemoteTables {
    fn standing(&self) -> StandingTableHandle<'_> {
        StandingTableHandle { imp: self.imp.get_table::<StandingRow>("standing"), ctx: std::marker::PhantomData }
    }
}

pub struct StandingInsertCallbackId(__sdk::CallbackId);
pub struct StandingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StandingTableHandle<'ctx> {
    type Row = StandingRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StandingRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StandingTableHandle<'ctx> {
    type Row = StandingRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StandingRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StandingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StandingInsertCallbackId {
        StandingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StandingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StandingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StandingDeleteCallbackId {
        StandingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StandingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StandingTableHandle<'ctx> {
    type InsertCallbackId = StandingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StandingInsertCallbackId {
        StandingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StandingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StandingTableHandle<'ctx> {
    type DeleteCallbackId = StandingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StandingDeleteCallbackId {
        StandingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StandingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StandingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StandingTableHandle<'ctx> {
    type UpdateCallbackId = StandingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StandingUpdateCallbackId {
        StandingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StandingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StandingTableHandle<'ctx> {
    type UpdateCallbackId = StandingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StandingUpdateCallbackId {
        StandingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StandingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player` unique index on the table `standing`,
/// which allows point queries on the field of the same name
/// via the [`StandingPlayerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.standing().player().find(...)`.
pub struct StandingPlayerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StandingRow, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StandingTableHandle<'ctx> {
    /// Get a handle on the `player` unique index on the table `standing`.
    pub fn player(&self) -> StandingPlayerUnique<'ctx> {
        StandingPlayerUnique { imp: self.imp.get_unique_constraint::<u16>("player"), phantom: std::marker::PhantomData }
    }
}

impl<'ctx> StandingPlayerUnique<'ctx> {
    /// Find the subscribed row whose `player` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<StandingRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StandingRow>("standing");
    _table.add_unique_constraint::<u16>("player", |row| &row.player);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<StandingRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<StandingRow>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StandingRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait standingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StandingRow`.
    fn standing(&self) -> __sdk::__query_builder::Table<StandingRow>;
}

impl standingQueryTableAccess for __sdk::QueryTableAccessor {
    fn standing(&self) -> __sdk::__query_builder::Table<StandingRow> {
        __sdk::__query_builder::Table::new("standing")
    }
}
