// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StandingRow {
    pub player: u16,
    pub team: u8,
    pub score: i32,
    pub deaths: u32,
    pub state: u8,
    pub due_tick: u64,
    pub spawns: u32,
    pub spawned_tick: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub penalty: u32,
}

impl __sdk::InModule for StandingRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StandingRow`.
///
/// Provides typed access to columns for query building.
pub struct StandingRowCols {
    pub player: __sdk::__query_builder::Col<StandingRow, u16>,
    pub team: __sdk::__query_builder::Col<StandingRow, u8>,
    pub score: __sdk::__query_builder::Col<StandingRow, i32>,
    pub deaths: __sdk::__query_builder::Col<StandingRow, u32>,
    pub state: __sdk::__query_builder::Col<StandingRow, u8>,
    pub due_tick: __sdk::__query_builder::Col<StandingRow, u64>,
    pub spawns: __sdk::__query_builder::Col<StandingRow, u32>,
    pub spawned_tick: __sdk::__query_builder::Col<StandingRow, u64>,
    pub x: __sdk::__query_builder::Col<StandingRow, f32>,
    pub y: __sdk::__query_builder::Col<StandingRow, f32>,
    pub z: __sdk::__query_builder::Col<StandingRow, f32>,
    pub yaw: __sdk::__query_builder::Col<StandingRow, f32>,
    pub penalty: __sdk::__query_builder::Col<StandingRow, u32>,
}

impl __sdk::__query_builder::HasCols for StandingRow {
    type Cols = StandingRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StandingRowCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            team: __sdk::__query_builder::Col::new(table_name, "team"),
            score: __sdk::__query_builder::Col::new(table_name, "score"),
            deaths: __sdk::__query_builder::Col::new(table_name, "deaths"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            due_tick: __sdk::__query_builder::Col::new(table_name, "due_tick"),
            spawns: __sdk::__query_builder::Col::new(table_name, "spawns"),
            spawned_tick: __sdk::__query_builder::Col::new(table_name, "spawned_tick"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            penalty: __sdk::__query_builder::Col::new(table_name, "penalty"),
        }
    }
}

/// Indexed column accessor struct for the table `StandingRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct StandingRowIxCols {
    pub player: __sdk::__query_builder::IxCol<StandingRow, u16>,
    pub state: __sdk::__query_builder::IxCol<StandingRow, u8>,
}

impl __sdk::__query_builder::HasIxCols for StandingRow {
    type IxCols = StandingRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StandingRowIxCols {
            player: __sdk::__query_builder::IxCol::new(table_name, "player"),
            state: __sdk::__query_builder::IxCol::new(table_name, "state"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StandingRow {}
