// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UseRequest {
    pub player: u16,
    pub slot: u8,
}

impl __sdk::InModule for UseRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UseRequest`.
///
/// Provides typed access to columns for query building.
pub struct UseRequestCols {
    pub player: __sdk::__query_builder::Col<UseRequest, u16>,
    pub slot: __sdk::__query_builder::Col<UseRequest, u8>,
}

impl __sdk::__query_builder::HasCols for UseRequest {
    type Cols = UseRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UseRequestCols {
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
        }
    }
}

/// Indexed column accessor struct for the table `UseRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct UseRequestIxCols {
    pub player: __sdk::__query_builder::IxCol<UseRequest, u16>,
}

impl __sdk::__query_builder::HasIxCols for UseRequest {
    type IxCols = UseRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UseRequestIxCols { player: __sdk::__query_builder::IxCol::new(table_name, "player") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UseRequest {}
