// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BanIdentityArgs {
    pub identity: __sdk::Identity,
    pub reason: String,
}

impl From<BanIdentityArgs> for super::Reducer {
    fn from(args: BanIdentityArgs) -> Self {
        Self::BanIdentity { identity: args.identity, reason: args.reason }
    }
}

impl __sdk::InModule for BanIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ban_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ban_identity {
    /// Request that the remote module invoke the reducer `ban_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ban_identity:ban_identity_then`] to run a callback after the reducer completes.
    fn ban_identity(&self, identity: __sdk::Identity, reason: String) -> __sdk::Result<()> {
        self.ban_identity_then(identity, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ban_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ban_identity_then(
        &self,
        identity: __sdk::Identity,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ban_identity for super::RemoteReducers {
    fn ban_identity_then(
        &self,
        identity: __sdk::Identity,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(BanIdentityArgs { identity, reason }, callback)
    }
}
