// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::banned_type::Banned;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `banned`.
///
/// Obtain a handle from the [`BannedTableAccess::banned`] method on [`super::RemoteTables`],
/// like `ctx.db.banned()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.banned().on_insert(...)`.
pub struct BannedTableHandle<'ctx> {
    imp: __sdk::TableHandle<Banned>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `banned`.
pub struct BannedTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BannedTableAccessor {
    type Row = Banned;
    type Handle<'db> = BannedTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.banned()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `banned`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BannedTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BannedTableHandle`], which mediates access to the table `banned`.
    fn banned(&self) -> BannedTableHandle<'_>;
}

impl BannedTableAccess for super::RemoteTables {
    fn banned(&self) -> BannedTableHandle<'_> {
        BannedTableHandle { imp: self.imp.get_table::<Banned>("banned"), ctx: std::marker::PhantomData }
    }
}

pub struct BannedInsertCallbackId(__sdk::CallbackId);
pub struct BannedDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BannedTableHandle<'ctx> {
    type Row = Banned;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Banned> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BannedTableHandle<'ctx> {
    type Row = Banned;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Banned> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BannedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BannedInsertCallbackId {
        BannedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BannedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BannedDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BannedDeleteCallbackId {
        BannedDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BannedDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BannedTableHandle<'ctx> {
    type InsertCallbackId = BannedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BannedInsertCallbackId {
        BannedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BannedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BannedTableHandle<'ctx> {
    type DeleteCallbackId = BannedDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BannedDeleteCallbackId {
        BannedDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BannedDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BannedUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BannedTableHandle<'ctx> {
    type UpdateCallbackId = BannedUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BannedUpdateCallbackId {
        BannedUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BannedUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BannedTableHandle<'ctx> {
    type UpdateCallbackId = BannedUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BannedUpdateCallbackId {
        BannedUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BannedUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `banned`,
/// which allows point queries on the field of the same name
/// via the [`BannedIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.banned().identity().find(...)`.
pub struct BannedIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Banned, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BannedTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `banned`.
    pub fn identity(&self) -> BannedIdentityUnique<'ctx> {
        BannedIdentityUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BannedIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Banned> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Banned>("banned");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<Banned>> {
    __sdk::TableUpdate::parse_table_update(raw_updates)
        .map_err(|e| __sdk::InternalError::failed_parse("TableUpdate<Banned>", "TableUpdate").with_cause(e).into())
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Banned`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait bannedQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Banned`.
    fn banned(&self) -> __sdk::__query_builder::Table<Banned>;
}

impl bannedQueryTableAccess for __sdk::QueryTableAccessor {
    fn banned(&self) -> __sdk::__query_builder::Table<Banned> {
        __sdk::__query_builder::Table::new("banned")
    }
}
