// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Banned {
    pub identity: __sdk::Identity,
    pub reason: String,
    pub banned_us: i64,
}

impl __sdk::InModule for Banned {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Banned`.
///
/// Provides typed access to columns for query building.
pub struct BannedCols {
    pub identity: __sdk::__query_builder::Col<Banned, __sdk::Identity>,
    pub reason: __sdk::__query_builder::Col<Banned, String>,
    pub banned_us: __sdk::__query_builder::Col<Banned, i64>,
}

impl __sdk::__query_builder::HasCols for Banned {
    type Cols = BannedCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BannedCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            banned_us: __sdk::__query_builder::Col::new(table_name, "banned_us"),
        }
    }
}

/// Indexed column accessor struct for the table `Banned`.
///
/// Provides typed access to indexed columns for query building.
pub struct BannedIxCols {
    pub identity: __sdk::__query_builder::IxCol<Banned, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Banned {
    type IxCols = BannedIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BannedIxCols { identity: __sdk::__query_builder::IxCol::new(table_name, "identity") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Banned {}
