// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::known_identity_type::KnownIdentity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `known_identity`.
///
/// Obtain a handle from the [`KnownIdentityTableAccess::known_identity`] method on [`super::RemoteTables`],
/// like `ctx.db.known_identity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.known_identity().on_insert(...)`.
pub struct KnownIdentityTableHandle<'ctx> {
    imp: __sdk::TableHandle<KnownIdentity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `known_identity`.
pub struct KnownIdentityTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for KnownIdentityTableAccessor {
    type Row = KnownIdentity;
    type Handle<'db> = KnownIdentityTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.known_identity()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `known_identity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KnownIdentityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KnownIdentityTableHandle`], which mediates access to the table `known_identity`.
    fn known_identity(&self) -> KnownIdentityTableHandle<'_>;
}

impl KnownIdentityTableAccess for super::RemoteTables {
    fn known_identity(&self) -> KnownIdentityTableHandle<'_> {
        KnownIdentityTableHandle {
            imp: self.imp.get_table::<KnownIdentity>("known_identity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct KnownIdentityInsertCallbackId(__sdk::CallbackId);
pub struct KnownIdentityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for KnownIdentityTableHandle<'ctx> {
    type Row = KnownIdentity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownIdentity> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for KnownIdentityTableHandle<'ctx> {
    type Row = KnownIdentity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnownIdentity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KnownIdentityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownIdentityInsertCallbackId {
        KnownIdentityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnownIdentityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KnownIdentityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownIdentityDeleteCallbackId {
        KnownIdentityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnownIdentityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for KnownIdentityTableHandle<'ctx> {
    type InsertCallbackId = KnownIdentityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownIdentityInsertCallbackId {
        KnownIdentityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnownIdentityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for KnownIdentityTableHandle<'ctx> {
    type DeleteCallbackId = KnownIdentityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnownIdentityDeleteCallbackId {
        KnownIdentityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnownIdentityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct KnownIdentityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KnownIdentityTableHandle<'ctx> {
    type UpdateCallbackId = KnownIdentityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnownIdentityUpdateCallbackId {
        KnownIdentityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnownIdentityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for KnownIdentityTableHandle<'ctx> {
    type UpdateCallbackId = KnownIdentityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnownIdentityUpdateCallbackId {
        KnownIdentityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnownIdentityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `known_identity`,
/// which allows point queries on the field of the same name
/// via the [`KnownIdentityIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.known_identity().identity().find(...)`.
pub struct KnownIdentityIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<KnownIdentity, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> KnownIdentityTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `known_identity`.
    pub fn identity(&self) -> KnownIdentityIdentityUnique<'ctx> {
        KnownIdentityIdentityUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> KnownIdentityIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<KnownIdentity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<KnownIdentity>("known_identity");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<KnownIdentity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<KnownIdentity>", "TableUpdate").with_cause(e).into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `KnownIdentity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait known_identityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `KnownIdentity`.
    fn known_identity(&self) -> __sdk::__query_builder::Table<KnownIdentity>;
}

impl known_identityQueryTableAccess for __sdk::QueryTableAccessor {
    fn known_identity(&self) -> __sdk::__query_builder::Table<KnownIdentity> {
        __sdk::__query_builder::Table::new("known_identity")
    }
}
