// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Server {
    pub id: String,
    pub title: String,
    pub map: String,
    pub game_type: String,
    pub variant: String,
    pub database: String,
    pub gateway: String,
    pub players: u32,
    pub capacity: u32,
    pub match_number: u64,
    pub match_seconds: u32,
    pub match_started_us: i64,
    pub updated_us: i64,
}

impl __sdk::InModule for Server {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Server`.
///
/// Provides typed access to columns for query building.
pub struct ServerCols {
    pub id: __sdk::__query_builder::Col<Server, String>,
    pub title: __sdk::__query_builder::Col<Server, String>,
    pub map: __sdk::__query_builder::Col<Server, String>,
    pub game_type: __sdk::__query_builder::Col<Server, String>,
    pub variant: __sdk::__query_builder::Col<Server, String>,
    pub database: __sdk::__query_builder::Col<Server, String>,
    pub gateway: __sdk::__query_builder::Col<Server, String>,
    pub players: __sdk::__query_builder::Col<Server, u32>,
    pub capacity: __sdk::__query_builder::Col<Server, u32>,
    pub match_number: __sdk::__query_builder::Col<Server, u64>,
    pub match_seconds: __sdk::__query_builder::Col<Server, u32>,
    pub match_started_us: __sdk::__query_builder::Col<Server, i64>,
    pub updated_us: __sdk::__query_builder::Col<Server, i64>,
}

impl __sdk::__query_builder::HasCols for Server {
    type Cols = ServerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ServerCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            map: __sdk::__query_builder::Col::new(table_name, "map"),
            game_type: __sdk::__query_builder::Col::new(table_name, "game_type"),
            variant: __sdk::__query_builder::Col::new(table_name, "variant"),
            database: __sdk::__query_builder::Col::new(table_name, "database"),
            gateway: __sdk::__query_builder::Col::new(table_name, "gateway"),
            players: __sdk::__query_builder::Col::new(table_name, "players"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            match_number: __sdk::__query_builder::Col::new(table_name, "match_number"),
            match_seconds: __sdk::__query_builder::Col::new(table_name, "match_seconds"),
            match_started_us: __sdk::__query_builder::Col::new(table_name, "match_started_us"),
            updated_us: __sdk::__query_builder::Col::new(table_name, "updated_us"),
        }
    }
}

/// Indexed column accessor struct for the table `Server`.
///
/// Provides typed access to indexed columns for query building.
pub struct ServerIxCols {
    pub id: __sdk::__query_builder::IxCol<Server, String>,
}

impl __sdk::__query_builder::HasIxCols for Server {
    type IxCols = ServerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ServerIxCols { id: __sdk::__query_builder::IxCol::new(table_name, "id") }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Server {}
