// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetServerPlayersArgs {
    pub id: String,
    pub players: u32,
}

impl From<SetServerPlayersArgs> for super::Reducer {
    fn from(args: SetServerPlayersArgs) -> Self {
        Self::SetServerPlayers { id: args.id, players: args.players }
    }
}

impl __sdk::InModule for SetServerPlayersArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_server_players`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_server_players {
    /// Request that the remote module invoke the reducer `set_server_players` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_server_players:set_server_players_then`] to run a callback after the reducer completes.
    fn set_server_players(&self, id: String, players: u32) -> __sdk::Result<()> {
        self.set_server_players_then(id, players, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_server_players` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_server_players_then(
        &self,
        id: String,
        players: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_server_players for super::RemoteReducers {
    fn set_server_players_then(
        &self,
        id: String,
        players: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetServerPlayersArgs { id, players }, callback)
    }
}
